// Generated by CoffeeScript 1.10.0
(function() {
  var assertDirEqual, metalsmith, path, resolve, stylus;

  path = require('path');

  resolve = path.resolve;

  assertDirEqual = require('assert-dir-equal');

  stylus = require('../');

  metalsmith = require('metalsmith');

  describe('metalsmith-styl', function() {
    return it('should compile stylus file', function(done) {
      var expected, source, target;
      source = resolve('./test/fixtures/basic/');
      target = resolve('./test/fixtures/basic/build');
      expected = resolve('./test/fixtures/basic/expected');
      return metalsmith(source).use(stylus()).build(function(err) {
        if (err) {
          done(err);
        }
        assertDirEqual(expected, target);
        return done();
      });
    });
  });

}).call(this);
