// Generated by CoffeeScript 1.10.0
(function() {
  var Stylus, basename, dirname, extend, extname, ref, stylus;

  ref = require('path'), basename = ref.basename, dirname = ref.dirname, extname = ref.extname;

  stylus = require('stylus');

  extend = (function(_this) {
    return function(object, properties) {
      var key, val;
      for (key in properties) {
        val = properties[key];
        object[key] = val;
      }
      return object;
    };
  })(this);

  Stylus = function(options) {
    var opts;
    opts = extend({
      master: null,
      output: 'master.css'
    }, options);
    return function(files, metalsmith, done) {
      var content, file, fn;
      fn = function(file, content) {
        var s;
        if (opts.master != null) {
          if (basename(file) === opts.master) {
            s = stylus(files[file].contents.toString()).set('filename', opts.output).include(process.cwd() + '/src/' + dirname(file));
            return s.render(function(err, css) {
              var new_file;
              if (err != null) {
                throw err;
              }
              new_file = file.replace(opts.master, opts.output);
              files[new_file] = files[file];
              files[new_file].contents = new Buffer(css);
              return delete files[file];
            });
          } else if (file.indexOf(opts.master) === -1) {
            return delete files[file];
          }
        } else {
          return s = stylus(files[file].contents.toString()).set('filename', basename(file)).include(process.cwd() + '/src/' + dirname(file)).render(function(err, css) {
            var new_file;
            if (err) {
              throw err;
            }
            new_file = file.replace('.styl', '.css');
            files[new_file] = files[file];
            files[new_file].contents = new Buffer(css);
            return delete files[file];
          });
        }
      };
      for (file in files) {
        content = files[file];
        fn(file, content);
      }
      return done();
    };
  };

  module.exports = Stylus;

}).call(this);
